### ISSUE TITLE
Why debian?

### ISSUE THREAD

**Issue by andr0d1v** [Xed-Editor/Karbon-Packages#1]
Alpine is a lightweight Linux distribution compared to Debian.

**Comment by RohitKushvaha01** [comment]
> Alpine is a lightweight Linux distribution compared to Debian.

1. Alpine doesn't have java 17
2. gcc crashes
3. Nodjs crashes
4. No Kotlin support
5. Most binaries won't work on alpine because it uses musl instead of glibc

**Comment by andr0d1v** [comment]
> > Alpine is a lightweight Linux distribution compared to Debian.
> 
> 1. Alpine doesn't have java 17
> 2. gcc crashes
> 3. Nodjs crashes
> 4. No Kotlin support
> 5. Most binaries won't work on alpine because it uses musl instead of glibc

About jdk17
![Screenshot_20240907-070404](https://github.com/user-attachments/assets/f88aff4c-26b8-479f-a3dc-9604bcf3eb09)
And it works. But Gradle not working

**Comment by RohitKushvaha01** [comment]
> > > Alpine is a lightweight Linux distribution compared to Debian.
> > 
> > 1. Alpine doesn't have java 17
> > 2. gcc crashes
> > 3. Nodjs crashes
> > 4. No Kotlin support
> > 5. Most binaries won't work on alpine because it uses musl instead of glibc
> 
> About jdk17
> ![Screenshot_20240907-070404](https://github.com/user-attachments/assets/f88aff4c-26b8-479f-a3dc-9604bcf3eb09)
> And it works. But Gradle not working

Good then

**Comment by andr0d1v** [comment]
Why did you remove it? If the java script and c++ crash for some reason, it doesn't mean that you can't cancel debian because java is running

**Comment by RohitKushvaha01** [comment]
> Why did you remove it? If the java script and c++ crash for some reason, it doesn't mean that you can't cancel debian because java is running

Fixed gcc and node, Proot was missing 
--link2symlink --ashmem-memfd --ashmem-memfd

Btw How did you installed java17? There's no package for java17 in the alpine stable branch

**Comment by andr0d1v** [comment]
> > Why did you remove it? If the java script and c++ crash for some reason, it doesn't mean that you can't cancel debian because java is running
> 
> Fixed gcc and node, Proot was missing --link2symlink --ashmem-memfd --ashmem-memfd
> 
> Btw How did you installed java17? There's no package for java17 in the alpine stable branch

```
apk add openjdk17
```
